version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      -"8080:8080"
    volumes:
      - ./backend:/app
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports: 
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app